ci_service: travis_ci
coverage_service: coveralls
xcodeproj: Marvel.xcodeproj
source_directory: .
ignore:
  - Pods/*
  - Tests/*
  - Carthage/*
output_directory: slather-report
html:
  show_line_numbers: true
